formation_promotion:
    resource: "@FormationBundle/Resources/config/routing/promotion.yml"
    prefix:   /promotion

formation_eleve:
    resource: "@FormationBundle/Resources/config/routing/eleve.yml"
    prefix:   /eleve

formation_intervenant:
    resource: "@FormationBundle/Resources/config/routing/intervenant.yml"
    prefix:   /intervenant

formation_module:
    resource: "@FormationBundle/Resources/config/routing/module.yml"
    prefix:   /module

formation_langage:
    resource: "@FormationBundle/Resources/config/routing/langage.yml"
    prefix:   /langage

formation_archive:
    resource: "@FormationBundle/Resources/config/routing/archive.yml"
    prefix:   /archive

formation_note:
    resource: "@FormationBundle/Resources/config/routing/note.yml"
    prefix:   /note

formation_commentaire:
    resource: "@FormationBundle/Resources/config/routing/commentaire.yml"
    prefix:   /commentaire



formation_homepage:
    path:     /{id}
    defaults: { _controller: FormationBundle:Default:index }
