<?php

namespace FormationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EleveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EleveRepository extends EntityRepository
{

    public function findByModule($module){
        $query = $this->createQueryBuilder('a')
            ->select('a')
            ->leftJoin('a.module', 'c')
            ->addSelect('c');

        $query = $query->add('where', $query->expr()->in('c', ':c'))
            ->setParameter('c', $module)
            ->getQuery()
            ->getResult();

        return $query;
    }
    
}
