<?php

namespace FormationBundle\Repository;

/**
 * ElevePromoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElevePromoRepository extends \Doctrine\ORM\EntityRepository
{
}
