<?php

namespace FormationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends EntityRepository
{
    public function findByPromo($promodule){
        $query = $this->createQueryBuilder('a')
            ->select('a')
            ->leftJoin('a.module', 'c')
            ->addSelect('c');

        $query = $query->add('where', $query->expr()->in('c', ':c'))
            ->setParameter('c', $promodule)
            ->getQuery()
            ->getResult();

        return $query;
    }

    public function findModule($eleve)
    {
        $qb = $this->createQueryBuilder('m');
        // On fait une jointure avec l'entité promotion avec pour alias « p »
        // attention a ne pas chercher de cette manier FormationBundle\Promotion 
        // car symfony s'occupe lui meme dans l'entité d'oú le e.promotion
        $qb
            ->join('m.eleve', 'e')
            ->addSelect('e')
        ;
        // Puis on filtre sur l'id des promotion
        $qb->where('m.id = :eleve');
        $qb->setParameter('eleve', $eleve);
        // Enfin, on retourne le résultat
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
