<?php

namespace FormationBundle\Repository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNotesByEleveprom($promotion, $ideleve)
    {
        $qb = $this->createQueryBuilder('n')
            ->delete('FormationBundle:Note', 'n')
            ->where('n.eleve = :eleve')
            ->setParameter('eleve', $ideleve)
            ->andWhere('n.promotion = :promo')
            ->setParameter('promo', $promotion)
            ->getQuery();

        $qb->execute();
    }
}
