FormationBundle\Entity\Commentaire:
    type: entity
    table: null
    repositoryClass: FormationBundle\Repository\CommentaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        message:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }

    manyToMany:
        eleve:
            targetEntity: FormationBundle\Entity\Eleve
            inversedBy: commentaire
            joinTable:
                name: com_elev
                joinColumns:
                    commentaire_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    eleve_id:
                        referencedColumnName: id

        promotion:
            targetEntity: FormationBundle\Entity\Promotion
            inversedBy: commentaire
            joinTable:
                name: com_promo
                joinColumns:
                    commentaire_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    promotion_id:
                        referencedColumnName: id

