FormationBundle\Entity\Commentaire:
    type: entity
    table: null
    repositoryClass: FormationBundle\Repository\CommentaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        message:
            type: string
            length: 255
    lifecycleCallbacks: {  }

    manyToMany:
        note:
            targetEntity: FormationBundle\Entity\Note
            mappedBy: commentaire

