FormationBundle\Entity\Eleve:
    type: entity
    table: null
    repositoryClass: FormationBundle\Repository\EleveRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
            nullable: true
        logo:
            type: string
            length: 255
            nullable: true
        adresse:
            type: string
            length: 255
            nullable: true
        cp:
            type: integer
            nullable: true
        ville:
            type: string
            length: 255
            nullable: true
        sexe:
            type: string
            length: 6
            nullable: true
        tel:
            type: integer
            nullable: true
        mail:
            type: string
            length: 255
            nullable: true
        datenaissance:
            type: date
            nullable: true
        archive:
            type: boolean
            nullable: true
        cv:
            type: string
            length: 255
            nullable: true
        cva:
            type: string
            length: 255
            nullable: true
        etude:
            type: string
            length: 10
            nullable: true
    lifecycleCallbacks:
      prePersist: [ preUpload, setCreatedAtValue, setExpiresAtValue ]
      preUpdate: [ preUpload, setUpdatedAtValue ]
      postPersist: [ upload ]
      postUpdate: [ upload ]
      postRemove: [ removeUpload ]

    manyToMany:
        promotion:
            targetEntity: FormationBundle\Entity\Promotion
            mappedBy: eleve

        module:
            targetEntity: FormationBundle\Entity\Module
            inversedBy: eleve
            joinTable:
                name: eleve_module
                joinColumns:
                    eleve_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    module_id:
                        referencedColumnName: id
