FormationBundle\Entity\Eleve:
    type: entity
    table: null
    repositoryClass: FormationBundle\Repository\EleveRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        logo:
            type: string
            length: 255
        adresse:
            type: string
            length: 255
        cp:
            type: integer
        ville:
            type: string
            length: 255
        tel:
            type: integer
        mail:
            type: string
            length: 255
        datenaissance:
            type: date
        archive:
            type: boolean
            nullable: true
    lifecycleCallbacks:
      prePersist: [ preUpload, setCreatedAtValue, setExpiresAtValue ]
      preUpdate: [ preUpload, setUpdatedAtValue ]
      postPersist: [ upload ]
      postUpdate: [ upload ]
      postRemove: [ removeUpload ]

    manyToMany:
        promotion:
            targetEntity: FormationBundle\Entity\Promotion
            mappedBy: eleve

        module:
            targetEntity: FormationBundle\Entity\Module
            inversedBy: eleve
            joinTable:
                name: eleve_module
                joinColumns:
                    eleve_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    module_id: