FormationBundle\Entity\Langage:
    type: entity
    table: null
    repositoryClass: FormationBundle\Repository\LangageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
    lifecycleCallbacks: {  }

    manyToMany:
        module:
            targetEntity: FormationBundle\Entity\Module
            inversedBy: langage
            joinTable:
                name: langage_module
                joinColumns:
                    langage_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    module_id:
