FormationBundle\Entity\Module:
    type: entity
    table: null
    repositoryClass: FormationBundle\Repository\ModuleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
    lifecycleCallbacks: {  }

    manyToMany:
        promotion:
            targetEntity: FormationBundle\Entity\Promotion
            mappedBy: module

        eleve:
            targetEntity: FormationBundle\Entity\Eleve
            mappedBy: module

        langage:
            targetEntity: FormationBundle\Entity\Langage
            mappedBy: module
