FormationBundle\Entity\Note:
    type: entity
    table: null
    repositoryClass: FormationBundle\Repository\NoteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        note:
            type: string
            length: '2'
    lifecycleCallbacks: {  }

    manyToOne:
        promotion:
            targetEntity: FormationBundle\Entity\Promotion
        eleve:
            targetEntity: FormationBundle\Entity\Eleve
        module:
            targetEntity: FormationBundle\Entity\Module

    manyToMany:
        commentaire:
            targetEntity: FormationBundle\Entity\Commentaire
            inversedBy: note
            joinTable:
                name: notecom
                joinColumns:
                    note_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    commentaire_id:
