FormationBundle\Entity\Promotion:
    type: entity
    table: null
    repositoryClass: FormationBundle\Repository\PromotionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
            unique: true
            nullable: true
        logo:
            type: string
            length: 255
            nullable: true
        formateur:
            type: string
            length: 255
            nullable: true
            column: prenom_form
            nullable: true
        semaines:
            type: string
            length: 255
            nullable: true
        dateDebut:
            type: date
            column: date_deb
            nullable: true
        dateFin:
            type: date
            column: date_fin
            nullable: true
        archive:
            type: boolean
            nullable: true
    lifecycleCallbacks:
      prePersist: [ preUpload, setCreatedAtValue, setExpiresAtValue ]
      preUpdate: [ preUpload, setUpdatedAtValue ]
      postPersist: [ upload ]
      postUpdate: [ upload ]
      postRemove: [ removeUpload ]

    manyToOne:
        langage:
            targetEntity: FormationBundle\Entity\Langage


    manyToMany:
        eleve:
            targetEntity: FormationBundle\Entity\Eleve
            inversedBy: promotion
            joinTable:
                name: prom_elev
                joinColumns:
                    promotion_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    eleve_id:

        module:
            targetEntity: FormationBundle\Entity\Module
            inversedBy: promotion
            joinTable:
                name: prom_module
                joinColumns:
                    promotion_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    module_id: