archive_index:
    path:     /
    defaults: { _controller: "FormationBundle:Archive:index" }
    methods:  GET

archive_prom:
    path:     /prom
    defaults: { _controller: "FormationBundle:Archive:prom" }
    methods:  GET